# Generated by Django 3.0.6 on 2020-05-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
